/// Public build configuration from `--dart-define-from-file=build/app_config.json`
/// (generated by tool/gen_app_config.dart from the APP_* keys in .env).
/// Only public values live here; server secrets never enter the app.
class AppConfig {
  const AppConfig._();

  static const environment = String.fromEnvironment('APP_ENV', defaultValue: 'staging');
  static const supabaseUrl = String.fromEnvironment('APP_SUPABASE_URL');
  static const supabaseKey = String.fromEnvironment('APP_SUPABASE_ANON_KEY');
  static const orgCode = String.fromEnvironment('APP_ORG_CODE', defaultValue: 'MAIN');

  static const firebaseProjectId = String.fromEnvironment('APP_FIREBASE_PROJECT_ID');
  static const firebaseSenderId = String.fromEnvironment('APP_FIREBASE_MESSAGING_SENDER_ID');
  static const firebaseAndroidApiKey = String.fromEnvironment('APP_FIREBASE_ANDROID_API_KEY');
  static const firebaseAndroidAppId = String.fromEnvironment('APP_FIREBASE_ANDROID_APP_ID');

  static bool get isProduction => environment == 'production';
  static bool get isConfigured => supabaseUrl.isNotEmpty && supabaseKey.isNotEmpty;
  static bool get pushConfigured => firebaseAndroidAppId.isNotEmpty && firebaseProjectId.isNotEmpty;
}
